-- you do not need this lua script, though it will allow you to with mgba 0.10 to export your pokemon to the calc
-- to use download this file on mgba select tools->scripting then file->open and open this file

move = {
	"-",
	"Pound",
	"Karate Chop",
	"Double Slap",
	"Comet Punch",
	"Mega Punch",
	"Pay Day",
	"Fire Punch",
	"Ice Punch",
	"ThunderPunch",
	"Scratch",
	"Vice Grip",
	"Guillotine",
	"Razor Wind",
	"Swords Dance",
	"Cut",
	"Gust",
	"Wing Attack",
	"Whirlwind",
	"Fly",
	"Bind",
	"Slam",
	"Vine Whip",
	"Stomp",
	"Double Kick",
	"Mega Kick",
	"Jump Kick",
	"Rolling Kick",
	"Sand Attack",
	"Headbutt",
	"Horn Attack",
	"Fury Attack",
	"Horn Drill",
	"Tackle",
	"Body Slam",
	"Wrap",
	"Take Down",
	"Thrash",
	"Double-Edge",
	"Tail Whip",
	"Poison Sting",
	"Twineedle",
	"Pin Missile",
	"Leer",
	"Bite",
	"Growl",
	"Roar",
	"Sing",
	"Supersonic",
	"Sonic Boom",
	"Disable",
	"Acid",
	"Ember",
	"Flamethrower",
	"Mist",
	"Water Gun",
	"Hydro Pump",
	"Surf",
	"Ice Beam",
	"Blizzard",
	"Psybeam",
	"Bubble Beam",
	"Aurora Beam",
	"Hyper Beam",
	"Peck",
	"Drill Peck",
	"Submission",
	"Low Kick",
	"Counter",
	"Seismic Toss",
	"Strength",
	"Absorb",
	"Mega Drain",
	"Leech Seed",
	"Growth",
	"Razor Leaf",
	"Solar Beam",
	"PoisonPowder",
	"Stun Spore",
	"Sleep Powder",
	"Petal Dance",
	"String Shot",
	"Dragon Rage",
	"Fire Spin",
	"ThunderShock",
	"Thunderbolt",
	"Thunder Wave",
	"Thunder",
	"Rock Throw",
	"Earthquake",
	"Fissure",
	"Dig",
	"Toxic",
	"Confusion",
	"Psychic",
	"Hypnosis",
	"Meditate",
	"Agility",
	"Quick Attack",
	"Rage",
	"Teleport",
	"Night Shade",
	"Mimic",
	"Screech",
	"Double Team",
	"Recover",
	"Harden",
	"Minimize",
	"Smokescreen",
	"Confuse Ray",
	"Withdraw",
	"Defense Curl",
	"Barrier",
	"Light Screen",
	"Haze",
	"Reflect",
	"Focus Energy",
	"Bide",
	"Metronome",
	"Mirror Move",
	"Selfdestruct",
	"Egg Bomb",
	"Lick",
	"Smog",
	"Sludge",
	"Bone Club",
	"Fire Blast",
	"Waterfall",
	"Clamp",
	"Swift",
	"Skull Bash",
	"Spike Cannon",
	"Constrict",
	"Amnesia",
	"Kinesis",
	"Soft-Boiled",
	"Hi Jump Kick",
	"Glare",
	"Dream Eater",
	"Poison Gas",
	"Barrage",
	"Leech Life",
	"Lovely Kiss",
	"Sky Attack",
	"Transform",
	"Bubble",
	"Dizzy Punch",
	"Spore",
	"Flash",
	"Psywave",
	"Splash",
	"Acid Armor",
	"Crabhammer",
	"Explosion",
	"Fury Swipes",
	"Bonemerang",
	"Rest",
	"Rock Slide",
	"Hyper Fang",
	"Sharpen",
	"Conversion",
	"Tri Attack",
	"Super Fang",
	"Slash",
	"Substitute",
	"Struggle",
	"Sketch",
	"Triple Kick",
	"Thief",
	"Spider Web",
	"Mind Reader",
	"Nightmare",
	"Flame Wheel",
	"Snore",
	"Curse",
	"Flail",
	"Conversion 2",
	"Aeroblast",
	"Cotton Spore",
	"Reversal",
	"Spite",
	"Powder Snow",
	"Protect",
	"Mach Punch",
	"Scary Face",
	"Feint Attack",
	"Sweet Kiss",
	"Belly Drum",
	"Sludge Bomb",
	"Mud-Slap",
	"Octazooka",
	"Spikes",
	"Zap Cannon",
	"Foresight",
	"Destiny Bond",
	"Perish Song",
	"Icy Wind",
	"Detect",
	"Bone Rush",
	"Lock-On",
	"Outrage",
	"Sandstorm",
	"Giga Drain",
	"Endure",
	"Charm",
	"Rollout",
	"False Swipe",
	"Swagger",
	"Milk Drink",
	"Spark",
	"Fury Cutter",
	"Steel Wing",
	"Mean Look",
	"Attract",
	"Sleep Talk",
	"Heal Bell",
	"Return",
	"Present",
	"Frustration",
	"Safeguard",
	"Pain Split",
	"Sacred Fire",
	"Magnitude",
	"DynamicPunch",
	"Megahorn",
	"DragonBreath",
	"Baton Pass",
	"Encore",
	"Pursuit",
	"Rapid Spin",
	"Sweet Scent",
	"Iron Tail",
	"Metal Claw",
	"Vital Throw",
	"Morning Sun",
	"Synthesis",
	"Moonlight",
	"Hidden Power",
	"Cross Chop",
	"Twister",
	"Rain Dance",
	"Sunny Day",
	"Crunch",
	"Mirror Coat",
	"Psych Up",
	"Extremespeed",
	"AncientPower",
	"Shadow Ball",
	"Future Sight",
	"Rock Smash",
	"Whirlpool",
	"Beat Up",
	"Fake Out",
	"Uproar",
	"Stockpile",
	"Spit Up",
	"Swallow",
	"Heat Wave",
	"Hail",
	"Torment",
	"Flatter",
	"Will-O-Wisp",
	"Memento",
	"Facade",
	"Focus Punch",
	"SmellingSalt",
	"Follow Me",
	"Nature Power",
	"Charge",
	"Taunt",
	"Helping Hand",
	"Trick",
	"Role Play",
	"Wish",
	"Assist",
	"Ingrain",
	"Superpower",
	"Magic Coat",
	"Recycle",
	"Revenge",
	"Brick Break",
	"Yawn",
	"Knock Off",
	"Endeavor",
	"Eruption",
	"Skill Swap",
	"Imprison",
	"Refresh",
	"Grudge",
	"Snatch",
	"Secret Power",
	"Dive",
	"Arm Thrust",
	"Camouflage",
	"Tail Glow",
	"Luster Purge",
	"Mist Ball",
	"FeatherDance",
	"Teeter Dance",
	"Blaze Kick",
	"Mud Sport",
	"Ice Ball",
	"Needle Arm",
	"Slack Off",
	"Hyper Voice",
	"Poison Fang",
	"Crush Claw",
	"Blast Burn",
	"Hydro Cannon",
	"Meteor Mash",
	"Astonish",
	"Weather Ball",
	"Aromatherapy",
	"Fake Tears",
	"Air Cutter",
	"Overheat",
	"Odor Sleuth",
	"Rock Tomb",
	"Silver Wind",
	"Metal Sound",
	"Grasswhistle",
	"Tickle",
	"Cosmic Power",
	"Water Spout",
	"Signal Beam",
	"Shadow Punch",
	"Extrasensory",
	"Sky Uppercut",
	"Sand Tomb",
	"Sheer Cold",
	"Muddy Water",
	"Bullet Seed",
	"Aerial Ace",
	"Icicle Spear",
	"Iron Defense",
	"Block",
	"Howl",
	"Dragon Claw",
	"Frenzy Plant",
	"Bulk Up",
	"Bounce",
	"Mud Shot",
	"Poison Tail",
	"Covet",
	"Volt Tackle",
	"Magical Leaf",
	"Water Sport",
	"Calm Mind",
	"Leaf Blade",
	"Dragon Dance",
	"Rock Blast",
	"Shock Wave",
	"Water Pulse",
	"Doom Desire",
	"Psycho Boost",
	"Leech Fang",
	"Air Slash",
	"Aqua Jet",
	"Aqua Tail",
	"Aura Sphere",
	"Avalanche",
	"Brave Bird",
	"Bug Buzz",
	"Bullet Punch",
	"Charge Beam",
	"Close Combat",
	"Cross Poison",
	"Dark Pulse",
	"Discharge",
	"Draco Meteor",
	"Dragon Pulse",
	"Drain Punch",
	"Earth Power",
	"Energy Ball",
	"Focus Blast",
	"Force Palm",
	"Giga Impact",
	"Grass Knot",
	"Gunk Shot",
	"Hammer Arm",
	"Head Smash",
	"Ice Shard",
	"Iron Head",
	"Lava Plume",
	"Magnet Bomb",
	"Mud Bomb",
	"Nasty Plot",
	"Night Slash",
	"Ominous Wind",
	"Power Gem",
	"Power Whip",
	"Psycho Cut",
	"Rock Climb",
	"Rock Polish",
	"Rock Wrecker",
	"Roost",
	"Seed Bomb",
	"Shadow Claw",
	"Shadow Sneak",
	"Vacuum Wave",
	"X-Scissor",
	"Zen Headbutt",
	"Switcheroo",
	"Drill Run",
	"Bulldoze",
	"Electroweb",
	"Flame Charge",
	"Frost Breath",
	"Heart Stamp",
	"Hone Claws",
	"Horn Leech",
	"Coil",
	"Hurricane",
	"Icicle Crash",
	"Work Up",
	"Quiver Dance",
	"Leaf Tornado",
	"Low Sweep",
	"Snarl",
	"Struggle Bug",
	"Steamroller",
	"Storm Throw",
	"Venoshock",
	"Wild Charge",
	"Poison Jab",
	"Acid Spray",
	"Fiery Dance",
	"Clear Smog",
	"Leaf Storm",
	"Stone Edge",
	"Payback",
	"Fire Fang",
	"Ice Fang",
	"Thunder Fang",
	"Flare Blitz",
	"Inferno",
	"Hex",
	"Dual Chop",
	"Double Hit",
	"Cotton Guard",
	"Acrobatics",
	"Flame Burst",
	"U-turn",
	"Volt Switch",
	"Dragon Tail",
	"Circle Throw",
	"Mirror Shot",
	"Wood Hammer",
	"Heal Pulse",
	"Flash Cannon",
	"Bug Bite",
	"Pluck",
	"Shell Smash",
	"Rage Powder",
	"Wake-Up Slap",
	"Razor Shell",
	"Copycat",
	"Miracle Eye",
	"Sucker Punch",
	"Scald",
	"Brine",
	"Fairy Wind",
	"Doll Eyes",
	"Play Rough",
	"Moonblast",
	"Drain Kiss",
	"Dazzle Gleam",
	"Disarm Cry",
	"Stealth Rock",
	"Toxic Spikes",
	"Healing Wish",
	"Lunar Dance",
	"Tailwind",
	"Boomburst",
	"Incinerate",
	"Worry Seed",
	"Gastro Acid",
	"Geomancy",
	"Flower Guard",
	"Rototiller",
	"Shift Gear",
	"Sticky Web",
	"Stored Power",
	"Acupressure",
	"Punishment",
	"Assurance",
	"Dragon Rush",
	"Dark Void",
	"Feint",
	"PhantomForce",
	"Petal Storm",
	"Play Nice",
	"Roar of Time",
	"Spacial Rend",
	"Magma Storm",
	"Final Gambit",
	"Shadow Force",
	"Nuzzle",
	"Retaliate",
	"Metal Bash",
	"Judgment",
	"Freeze-Dry",
	"Psyshock",
	"Round",
	"Tail Slap",
	"Gear Grind",
	"Natural Gift",
	"Chip Away",
	"Smack Down",
	"Space Hole",
	"Gyro Ball",
	"Space Fury",
	"Attack Order",
	"Defend Order",
	"Heal Order",
	"Captivate",
	"Defog",
	"Origin Pulse",
	"Cliff Blades",
	"Guard Swap",
	"Steam Pump",
	"Metal Burst",
	"Me First",
	"Power Swap",
	"Power Trick",
	"Psycho Shift",
	"Wring Out",
	"Kings Shield",
	"Psystrike",
	"Autotomize",
	"DiamondStorm",
	"Sludge Wave",
	"Heavy Slam",
	"Synchronoise",
	"Electro Ball",
	"Foul Play",
	"Entrainment",
	"Night Daze",
	"Echoed Voice",
	"Land's Wrath",
	"OblivionWing",
	"Heart Swap",
	"Crush Grip",
	"Sacred Sword",
	"Heat Crash",
	"Head Charge",
	"Techno Blast",
	"Relic Song",
	"Secret Sword",
	"Glaciate",
	"Bolt Strike",
	"Blue Flare",
	"Freeze Shock",
	"Ice Burn",
	"V-create",
	"Fusion Flare",
	"Fusion Bolt",
	"Fell Stinger",
	"Noble Roar",
	"Dragon Rise",
	"Parting Shot",
	"Topsy-Turvy",
	"Core Enforce",
	"Chatter",
	"Confide",
	"Water Star",
	"Mystic Fire",
	"Spiky Shield",
	"EerieImpulse",
	"Hold Back",
	"Infestation",
	"Power-Up Hit",
	"1000 Arrows",
	"1000 Waves",
	"Para Charge",
	"Searing Shot",
	"Seed Flare",
	"Accelerock",
	"Anchor Shot",
	"Aurora Veil",
	"Baneful Bunk",
	"Beak Blast",
	"Brutal Swing",
	"Burn Up",
	"Clang Scales",
	"Dark Lariat",
	"Draco Hammer",
	"Fire Lash",
	"First Press",
	"Fleur Cannon",
	"Floral Heal",
	"Gear Up",
	"Horsepower",
	"Ice Hammer",
	"Laser Focus",
	"Leafage",
	"Liquidation",
	"Lunge",
	"Geist Beam",
	"Multi-Attack",
	"Nature's Mad",
	"Pollen Puff",
	"Power Trip",
	"Prism Laser",
	"Psychic Fang",
	"Purify",
	"Revel Dance",
	"Shadow Bone",
	"Shell Trap",
	"Shore Up",
	"Smart Strike",
	"Solar Blade",
	"Sparkle Aria",
	"Spect Thief",
	"Speed Swap",
	"Spirit Lock",
	"Spotlight",
	"Bad Tantrum",
	"Strength Sap",
	"Sunsteel Ram",
	"Teary Look",
	"Throat Chop",
	"Toxic Thread",
	"Trop Kick",
	"Zing Zap",
	"Elec Terrain",
	"Gras Terrain",
	"Mist Terrain",
	"Psyc Terrain",
	"Grass Pledge",
	"Fire Pledge",
	"Water Pledge",
	"Trick Room",
	"Magic Room",
	"Wonder Room",
	"Crafty Guard",
	"Mat Block",
	"Quick Guard",
	"Wide Guard",
	"Aqua Ring",
	"Aroma Mist",
	"Belch",
	"Bestow",
	"Fling",
	"Flying Press",
	"Gravity",
	"Guard Split",
	"Heal Block",
	"Ion Deluge",
	"Lucky Chant",
	"Magnet Rise",
	"Magnet Flux",
	"Powder",
	"Power Split",
	"Reflect Type",
	"Simple Beam",
	"Soak",
	"Telekinesis",
	"TrickoTreat",
	"Venom Drench",
	"Woods Curse",
	"Mind Blown",
	"PhotonGeyser",
	"Plasma Fists",
	"Electrify",
	"Embargo",
	"Fairy Lock",
	"Light o Ruin",
	"Trump Card",
	"After You",
	"Instruct",
	"Quash",
	"Happy Hour",
	"Double Iron",
	"Last Resort",
	"Sky Drop",
	"Celebrate",
	"Hold Hands",
	"DMax Cannon",
	"Snipe Shot",
	"Jaw Lock",
	"Stuff Cheeks",
	"No Retreat",
	"Tar Shot",
	"Magic Powder",
	"Dragon Darts",
	"Teatime",
	"Octolock",
	"Bolt Beak",
	"Fishy Rend",
	"Court Change",
	"Clang Soul",
	"Body Press",
	"Decorate",
	"Drum Beating",
	"Snap Trap",
	"Pyro Ball",
	"Giant Blade",
	"Giant Bash",
	"Aura Wheel",
	"Break Swipe",
	"Branch Poke",
	"Overdrive",
	"Apple Acid",
	"Grav Apple",
	"Spirit Break",
	"Weird Steam",
	"Life Dew",
	"Obstruct",
	"False Yield",
	"Meteor Rush",
	"Eternabeam",
	"Steel Beam",
	"Expand Force",
	"Steel Roller",
	"Scale Shot",
	"Meteor Beam",
	"ShellSideArm",
	"MistyExplode",
	"Grassy Glide",
	"Rising Volt",
	"TerrainPulse",
	"SkitterSmack",
	"Jealous Burn",
	"Lash Out",
	"Poltergeist",
	"Corrode Gas",
	"Coaching",
	"Flip Turn",
	"Triple Axel",
	"DualWingbeat",
	"Scorch Sands",
	"Jungle Heal",
	"Wicked Blow",
	"SurgeStrikes",
	"Freeze Glare",
	"Thunder Kick",
	"Fiery Wrath",
	"Thunder Cage",
	"DragonEnergy",
	"Z-Move 1",
	"Z-Move 2",
	"Z-Move 3",
	"Z-Move 4",
	"Z-Move 5",
	"Z-Move 6",
	"Z-Move 7",
	"Z-Move 8",
	"Z-Move 9",
	"Z-Move 10",
	"Z-Move 11",
	"Z-Move 12",
	"Z-Move 13",
	"Z-Move 14",
	"Z-Move 15",
	"Z-Move 16",
	"Z-Move 17",
	"Z-Move 18",
	"Z-Move 19",
	"Z-Move 20",
	"Z-Move 21",
	"Z-Move 22",
	"Z-Move 23",
	"Z-Move 24",
	"Z-Move 25",
	"Z-Move 26",
	"Z-Move 27",
	"Z-Move 28",
	"Z-Move 29",
	"Z-Move 30",
	"Z-Move 31",
	"Z-Move 32",
	"Z-Move 33",
	"Z-Move 34",
	"Z-Move 35",
	"Z-Move 36",
	"Z-Move 37",
	"Z-Move 38",
	"Z-Move 39",
	"Z-Move 40",
	"Z-Move 41",
	"Z-Move 42",
	"Z-Move 43",
	"Z-Move 44",
	"Z-Move 45",
	"Z-Move 46",
	"Z-Move 47",
	"Z-Move 48",
	"Z-Move 49",
	"Z-Move 50",
	"Z-Move 51",
	"Z-Move 52",
	"Z-Move 53",
	"Guard",
	"Strike",
	"Strike",
	"Knuckle",
	"Knuckle",
	"Airstream",
	"Airstream",
	"Ooze",
	"Ooze",
	"Quake",
	"Quake",
	"Rockfall",
	"Rockfall",
	"Flutterby",
	"Flutterby",
	"Phantasm",
	"Phantasm",
	"Steelspike",
	"Steelspike",
	"Flare",
	"Flare",
	"Geyser",
	"Geyser",
	"Overgrowth",
	"Overgrowth",
	"Lightning",
	"Lightning",
	"Mindstorm",
	"Mindstorm",
	"Hailstorm",
	"Hailstorm",
	"Wyrmwind",
	"Wyrmwind",
	"Darkness",
	"Darkness",
	"Starfall",
	"Starfall",
	"Vine Lash",
	"Vine Lash",
	"Wildfire",
	"Wildfire",
	"Cannonade",
	"Cannonade",
	"Befuddle",
	"Befuddle",
	"Voltcrash",
	"Voltcrash",
	"Goldrush",
	"Goldrush",
	"Chistrike",
	"Chistrike",
	"Terror",
	"Terror",
	"Foamburst",
	"Foamburst",
	"Resonance",
	"Resonance",
	"Cuddle",
	"Cuddle",
	"Replenish",
	"Replenish",
	"Malodor",
	"Malodor",
	"Meltdown",
	"Meltdown",
	"Drum Solo",
	"Drum Solo",
	"Fireball",
	"Fireball",
	"Hydrosnipe",
	"Hydrosnipe",
	"Windrage",
	"Windrage",
	"Gravitas",
	"Gravitas",
	"Stonesurge",
	"Stonesurge",
	"Volcalith",
	"Volcalith",
	"Tartness",
	"Tartness",
	"Sweetness",
	"Sweetness",
	"Sandblast",
	"Sandblast",
	"Stunshock",
	"Stunshock",
	"Centiferno",
	"Centiferno",
	"Smite",
	"Smite",
	"Snooze",
	"Snooze",
	"Finale",
	"Finale",
	"Steelsurge",
	"Steelsurge",
	"Depletion",
	"Depletion",
	"One Blow",
	"One Blow",
	"Rapid Flow",
	"Rapid Flow",
}

mons = {
	"Bulbasaur",
	"Ivysaur",
	"Venusaur",
	"Charmander",
	"Charmeleon",
	"Charizard",
	"Squirtle",
	"Wartortle",
	"Blastoise",
	"Caterpie",
	"Metapod",
	"Butterfree",
	"Weedle",
	"Kakuna",
	"Beedrill",
	"Pidgey",
	"Pidgeotto",
	"Pidgeot",
	"Rattata",
	"Raticate",
	"Spearow",
	"Fearow",
	"Ekans",
	"Arbok",
	"Pikachu",
	"Raichu",
	"Sandshrew",
	"Sandslash",
	"Nidoran-F",
	"Nidorina",
	"Nidoqueen",
	"Nidoran-M",
	"Nidorino",
	"Nidoking",
	"Clefairy",
	"Clefable",
	"Vulpix",
	"Ninetales",
	"Jigglypuff",
	"Wigglytuff",
	"Zubat",
	"Golbat",
	"Oddish",
	"Gloom",
	"Vileplume",
	"Paras",
	"Parasect",
	"Venonat",
	"Venomoth",
	"Diglett",
	"Dugtrio",
	"Meowth",
	"Persian",
	"Psyduck",
	"Golduck",
	"Mankey",
	"Primeape",
	"Growlithe",
	"Arcanine",
	"Poliwag",
	"Poliwhirl",
	"Poliwrath",
	"Abra",
	"Kadabra",
	"Alakazam",
	"Machop",
	"Machoke",
	"Machamp",
	"Bellsprout",
	"Weepinbell",
	"Victreebel",
	"Tentacool",
	"Tentacruel",
	"Geodude",
	"Graveler",
	"Golem",
	"Ponyta",
	"Rapidash",
	"Slowpoke",
	"Slowbro",
	"Magnemite",
	"Magneton",
	"Farfetch'd",
	"Doduo",
	"Dodrio",
	"Seel",
	"Dewgong",
	"Grimer",
	"Muk",
	"Shellder",
	"Cloyster",
	"Gastly",
	"Haunter",
	"Gengar",
	"Onix",
	"Drowzee",
	"Hypno",
	"Krabby",
	"Kingler",
	"Voltorb",
	"Electrode",
	"Exeggcute",
	"Exeggutor",
	"Cubone",
	"Marowak",
	"Hitmonlee",
	"Hitmonchan",
	"Lickitung",
	"Koffing",
	"Weezing",
	"Rhyhorn",
	"Rhydon",
	"Chansey",
	"Tangela",
	"Kangaskhan",
	"Horsea",
	"Seadra",
	"Goldeen",
	"Seaking",
	"Staryu",
	"Starmie",
	"Mr. Mime",
	"Scyther",
	"Jynx",
	"Electabuzz",
	"Magmar",
	"Pinsir",
	"Tauros",
	"Magikarp",
	"Gyarados",
	"Lapras",
	"Ditto",
	"Eevee",
	"Vaporeon",
	"Jolteon",
	"Flareon",
	"Porygon",
	"Omanyte",
	"Omastar",
	"Kabuto",
	"Kabutops",
	"Aerodactyl",
	"Snorlax",
	"Articuno",
	"Zapdos",
	"Moltres",
	"Dratini",
	"Dragonair",
	"Dragonite",
	"Mewtwo",
	"Mew",
	"Chikorita",
	"Bayleef",
	"Meganium",
	"Cyndaquil",
	"Quilava",
	"Typhlosion",
	"Totodile",
	"Croconaw",
	"Feraligatr",
	"Sentret",
	"Furret",
	"Hoothoot",
	"Noctowl",
	"Ledyba",
	"Ledian",
	"Spinarak",
	"Ariados",
	"Crobat",
	"Chinchou",
	"Lanturn",
	"Pichu",
	"Cleffa",
	"Igglybuff",
	"Togepi",
	"Togetic",
	"Natu",
	"Xatu",
	"Mareep",
	"Flaaffy",
	"Ampharos",
	"Bellossom",
	"Marill",
	"Azumarill",
	"Sudowoodo",
	"Politoed",
	"Hoppip",
	"Skiploom",
	"Jumpluff",
	"Aipom",
	"Sunkern",
	"Sunflora",
	"Yanma",
	"Wooper",
	"Quagsire",
	"Espeon",
	"Umbreon",
	"Murkrow",
	"Slowking",
	"Misdreavus",
	"Unown",
	"Wobbuffet",
	"Girafarig",
	"Pineco",
	"Forretress",
	"Dunsparce",
	"Gligar",
	"Steelix",
	"Snubbull",
	"Granbull",
	"Qwilfish",
	"Scizor",
	"Shuckle",
	"Heracross",
	"Sneasel",
	"Teddiursa",
	"Ursaring",
	"Slugma",
	"Magcargo",
	"Swinub",
	"Piloswine",
	"Corsola",
	"Remoraid",
	"Octillery",
	"Delibird",
	"Mantine",
	"Skarmory",
	"Houndour",
	"Houndoom",
	"Kingdra",
	"Phanpy",
	"Donphan",
	"Porygon2",
	"Stantler",
	"Smeargle",
	"Tyrogue",
	"Hitmontop",
	"Smoochum",
	"Elekid",
	"Magby",
	"Miltank",
	"Blissey",
	"Raikou",
	"Entei",
	"Suicune",
	"Larvitar",
	"Pupitar",
	"Tyranitar",
	"Lugia",
	"Ho-Oh",
	"Celebi",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"Treecko",
	"Grovyle",
	"Sceptile",
	"Torchic",
	"Combusken",
	"Blaziken",
	"Mudkip",
	"Marshtomp",
	"Swampert",
	"Poochyena",
	"Mightyena",
	"Zigzagoon",
	"Linoone",
	"Wurmple",
	"Silcoon",
	"Beautifly",
	"Cascoon",
	"Dustox",
	"Lotad",
	"Lombre",
	"Ludicolo",
	"Seedot",
	"Nuzleaf",
	"Shiftry",
	"Nincada",
	"Ninjask",
	"Shedinja",
	"Taillow",
	"Swellow",
	"Shroomish",
	"Breloom",
	"Spinda",
	"Wingull",
	"Pelipper",
	"Surskit",
	"Masquerain",
	"Wailmer",
	"Wailord",
	"Skitty",
	"Delcatty",
	"Kecleon",
	"Baltoy",
	"Claydol",
	"Nosepass",
	"Torkoal",
	"Sableye",
	"Barboach",
	"Whiscash",
	"Luvdisc",
	"Corphish",
	"Crawdaunt",
	"Feebas",
	"Milotic",
	"Carvanha",
	"Sharpedo",
	"Trapinch",
	"Vibrava",
	"Flygon",
	"Makuhita",
	"Hariyama",
	"Electrike",
	"Manectric",
	"Numel",
	"Camerupt",
	"Spheal",
	"Sealeo",
	"Walrein",
	"Cacnea",
	"Cacturne",
	"Snorunt",
	"Glalie",
	"Lunatone",
	"Solrock",
	"Azurill",
	"Spoink",
	"Grumpig",
	"Plusle",
	"Minun",
	"Mawile",
	"Meditite",
	"Medicham",
	"Swablu",
	"Altaria",
	"Wynaut",
	"Duskull",
	"Dusclops",
	"Roselia",
	"Slakoth",
	"Vigoroth",
	"Slaking",
	"Gulpin",
	"Swalot",
	"Tropius",
	"Whismur",
	"Loudred",
	"Exploud",
	"Clamperl",
	"Huntail",
	"Gorebyss",
	"Absol",
	"Shuppet",
	"Banette",
	"Seviper",
	"Zangoose",
	"Relicanth",
	"Aron",
	"Lairon",
	"Aggron",
	"Castform",
	"Volbeat",
	"Illumise",
	"Lileep",
	"Cradily",
	"Anorith",
	"Armaldo",
	"Ralts",
	"Kirlia",
	"Gardevoir",
	"Bagon",
	"Shelgon",
	"Salamence",
	"Beldum",
	"Metang",
	"Metagross",
	"Regirock",
	"Regice",
	"Registeel",
	"Kyogre",
	"Groudon",
	"Rayquaza",
	"Latias",
	"Latios",
	"Jirachi",
	"Deoxys",
	"Chimecho",
	"Bad Egg",
	"Unown B",
	"Unown C",
	"Unown D",
	"Unown E",
	"Unown F",
	"Unown G",
	"Unown H",
	"Unown I",
	"Unown J",
	"Unown K",
	"Unown L",
	"Unown M",
	"Unown N",
	"Unown O",
	"Unown P",
	"Unown Q",
	"Unown R",
	"Unown S",
	"Unown T",
	"Unown U",
	"Unown V",
	"Unown W",
	"Unown X",
	"Unown Y",
	"Unown Z",
	"Unown !",
	"Unown ?",
	"Turtwig",
	"Grotle",
	"Torterra",
	"Chimchar",
	"Monferno",
	"Infernape",
	"Piplup",
	"Prinplup",
	"Empoleon",
	"Starly",
	"Staravia",
	"Staraptor",
	"Bidoof",
	"Bibarel",
	"Kricketot",
	"Kricketune",
	"Shinx",
	"Luxio",
	"Luxray",
	"Budew",
	"Roserade",
	"Cranidos",
	"Rampardos",
	"Shieldon",
	"Bastiodon",
	"Burmy",
	"Wormadam",
	"Mothim",
	"Combee",
	"Vespiquen",
	"Pachirisu",
	"Buizel",
	"Floatzel",
	"Cherubi",
	"Cherrim",
	"Shellos",
	"Gastrodon",
	"Ambipom",
	"Drifloon",
	"Drifblim",
	"Buneary",
	"Lopunny",
	"Mismagius",
	"Honchkrow",
	"Glameow",
	"Purugly",
	"Chingling",
	"Stunky",
	"Skuntank",
	"Bronzor",
	"Bronzong",
	"Bonsly",
	"Mime Jr.",
	"Happiny",
	"Chatot",
	"Spiritomb",
	"Gible",
	"Gabite",
	"Garchomp",
	"Munchlax",
	"Riolu",
	"Lucario",
	"Hippopotas",
	"Hippowdon",
	"Skorupi",
	"Drapion",
	"Croagunk",
	"Toxicroak",
	"Carnivine",
	"Finneon",
	"Lumineon",
	"Mantyke",
	"Snover",
	"Abomasnow",
	"Weavile",
	"Magnezone",
	"Lickilicky",
	"Rhyperior",
	"Tangrowth",
	"Electivire",
	"Magmortar",
	"Togekiss",
	"Yanmega",
	"Leafeon",
	"Glaceon",
	"Gliscor",
	"Mamoswine",
	"Porygon-Z",
	"Gallade",
	"Probopass",
	"Dusknoir",
	"Froslass",
	"Rotom",
	"Uxie",
	"Mesprit",
	"Azelf",
	"Dialga",
	"Palkia",
	"Heatran",
	"Regigigas",
	"Giratina",
	"Cresselia",
	"Phione",
	"Manaphy",
	"Darkrai",
	"Shaymin",
	"Arceus",
	"Victini",
	"Snivy",
	"Servine",
	"Serperior",
	"Tepig",
	"Pignite",
	"Emboar",
	"Oshawott",
	"Dewott",
	"Samurott",
	"Patrat",
	"Watchog",
	"Lillipup",
	"Herdier",
	"Stoutland",
	"Purrloin",
	"Liepard",
	"Pansage",
	"Simisage",
	"Pansear",
	"Simisear",
	"Panpour",
	"Simipour",
	"Munna",
	"Musharna",
	"Pidove",
	"Tranquill",
	"Unfezant",
	"Blitzle",
	"Zebstrika",
	"Roggenrola",
	"Boldore",
	"Gigalith",
	"Woobat",
	"Swoobat",
	"Drilbur",
	"Excadrill",
	"Audino",
	"Timburr",
	"Gurdurr",
	"Conkeldurr",
	"Tympole",
	"Palpitoad",
	"Seismitoad",
	"Throh",
	"Sawk",
	"Sewaddle",
	"Swadloon",
	"Leavanny",
	"Venipede",
	"Whirlipede",
	"Scolipede",
	"Cottonee",
	"Whimsicott",
	"Petilil",
	"Lilligant",
	"Basculin",
	"Sandile",
	"Krokorok",
	"Krookodile",
	"Darumaka",
	"Darmanitan",
	"Maractus",
	"Dwebble",
	"Crustle",
	"Scraggy",
	"Scrafty",
	"Sigilyph",
	"Yamask",
	"Cofagrigus",
	"Tirtouga",
	"Carracosta",
	"Archen",
	"Archeops",
	"Trubbish",
	"Garbodor",
	"Zorua",
	"Zoroark",
	"Minccino",
	"Cinccino",
	"Gothita",
	"Gothorita",
	"Gothitelle",
	"Solosis",
	"Duosion",
	"Reuniclus",
	"Ducklett",
	"Swanna",
	"Vanillite",
	"Vanillish",
	"Vanilluxe",
	"Deerling",
	"Sawsbuck",
	"Emolga",
	"Karrablast",
	"Escavalier",
	"Foongus",
	"Amoonguss",
	"Frillish",
	"Jellicent",
	"Alomomola",
	"Joltik",
	"Galvantula",
	"Ferroseed",
	"Ferrothorn",
	"Klink",
	"Klang",
	"Klinklang",
	"Tynamo",
	"Eelektrik",
	"Eelektross",
	"Elgyem",
	"Beheeyem",
	"Litwick",
	"Lampent",
	"Chandelure",
	"Axew",
	"Fraxure",
	"Haxorus",
	"Cubchoo",
	"Beartic",
	"Cryogonal",
	"Shelmet",
	"Accelgor",
	"Stunfisk",
	"Mienfoo",
	"Mienshao",
	"Druddigon",
	"Golett",
	"Golurk",
	"Pawniard",
	"Bisharp",
	"Bouffalant",
	"Rufflet",
	"Braviary",
	"Vullaby",
	"Mandibuzz",
	"Heatmor",
	"Durant",
	"Deino",
	"Zweilous",
	"Hydreigon",
	"Larvesta",
	"Volcarona",
	"Cobalion",
	"Terrakion",
	"Virizion",
	"Tornadus",
	"Thundurus",
	"Reshiram",
	"Zekrom",
	"Landorus",
	"Kyurem",
	"Keldeo",
	"Meloetta",
	"Genesect",
	"Unfezant",
	"Frillish",
	"Jellicent",
	"Warrior",
	"Burmy",
	"Burmy",
	"Wormadam",
	"Wormadam",
	"Shellos",
	"Gastrodon",
	"Rotom",
	"Rotom",
	"Rotom",
	"Rotom",
	"Rotom",
	"Giratina",
	"Shaymin",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Arceus",
	"Basculin",
	"Darmanitan",
	"Deerling",
	"Deerling",
	"Deerling",
	"Sawsbuck",
	"Sawsbuck",
	"Sawsbuck",
	"Hippopotas",
	"Hippowdon",
	"Meloetta",
	"Genesect",
	"Genesect",
	"Genesect",
	"Genesect",
	"Cherrim",
	"Kyurem",
	"Kyurem",
	"Tornadus",
	"Thundurus",
	"Landorus",
	"Keldeo",
	"Chespin",
	"Quilladin",
	"Chesnaught",
	"Fennekin",
	"Braixen",
	"Delphox",
	"Froakie",
	"Frogadier",
	"Greninja",
	"Bunnelby",
	"Diggersby",
	"Fletchling",
	"Fletchindr",
	"Talonflame",
	"Scatterbug",
	"Spewpa",
	"Vivillon",
	"Litleo",
	"Pyroar",
	"Flabébé",
	"Floette",
	"Florges",
	"Skiddo",
	"Gogoat",
	"Pancham",
	"Pangoro",
	"Furfrou",
	"Espurr",
	"Meowstic",
	"Honedge",
	"Doublade",
	"Aegislash",
	"Spritzee",
	"Aromatisse",
	"Swirlix",
	"Slurpuff",
	"Inkay",
	"Malamar",
	"Binacle",
	"Barbaracle",
	"Skrelp",
	"Dragalge",
	"Clauncher",
	"Clawitzer",
	"Helioptile",
	"Heliolisk",
	"Tyrunt",
	"Tyrantrum",
	"Amaura",
	"Aurorus",
	"Sylveon",
	"Hawlucha",
	"Dedenne",
	"Carbink",
	"Goomy",
	"Sliggoo",
	"Goodra",
	"Klefki",
	"Phantump",
	"Trevenant",
	"Pumpkaboo",
	"Gourgeist",
	"Bergmite",
	"Avalugg",
	"Noibat",
}

item = {
	"MASTER BALL",
	"ULTRA BALL",
	"GREAT BALL",
	"POKé BALL",
	"SAFARI BALL",
	"NET BALL",
	"DIVE BALL",
	"NEST BALL",
	"REPEAT BALL",
	"TIMER BALL",
	"LUXURY BALL",
	"PREMIER BALL",
	"POTION",
	"ANTIDOTE",
	"BURN HEAL",
	"ICE HEAL",
	"AWAKENING",
	"PARLYZ HEAL",
	"FULL RESTORE",
	"MAX POTION",
	"HYPER POTION",
	"SUPER POTION",
	"FULL HEAL",
	"REVIVE",
	"MAX REVIVE",
	"FRESH WATER",
	"SODA POP",
	"LEMONADE",
	"MOOMOO MILK",
	"ENERGYPOWDER",
	"ENERGY ROOT",
	"HEAL POWDER",
	"REVIVAL HERB",
	"ETHER",
	"MAX ETHER",
	"ELIXIR",
	"MAX ELIXIR",
	"LAVA COOKIE",
	"BLUE FLUTE",
	"YELLOW FLUTE",
	"RED FLUTE",
	"BLACK FLUTE",
	"WHITE FLUTE",
	"BERRY JUICE",
	"SACRED ASH",
	"SHOAL SALT",
	"SHOAL SHELL",
	"RED SHARD",
	"BLUE SHARD",
	"YELLOW SHARD",
	"GREEN SHARD",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"HP4",
	"Attack4",
	"Defense4",
	"Speed4",
	"Sp. Atk4",
	"EndlessCandy",
	"PP UP",
	"Sp. Def4",
	"PP MAX",
	"????????",
	"GUARD SPEC.",
	"HP32",
	"Attack32",
	"Defense32",
	"Speed32",
	"Sp. Atk32",
	"Sp. Def32",
	"POKé DOLL",
	"FLUFFY TAIL",
	"????????",
	"SUPER REPEL",
	"EndlessRepel",
	"ESCAPE ROPE",
	"REPEL",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"SUN STONE",
	"MOON STONE",
	"FIRE STONE",
	"THUNDERSTONE",
	"WATER STONE",
	"LEAF STONE",
	"????????",
	"????????",
	"????????",
	"????????",
	"TINYMUSHROOM",
	"BIG MUSHROOM",
	"????????",
	"PEARL",
	"BIG PEARL",
	"STARDUST",
	"STAR PIECE",
	"NUGGET",
	"HEART SCALE",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"ORANGE MAIL",
	"HARBOR MAIL",
	"GLITTER MAIL",
	"MECH MAIL",
	"WOOD MAIL",
	"WAVE MAIL",
	"BEAD MAIL",
	"SHADOW MAIL",
	"TROPIC MAIL",
	"DREAM MAIL",
	"FAB MAIL",
	"RETRO MAIL",
	"CHERI BERRY",
	"CHESTO BERRY",
	"PECHA BERRY",
	"RAWST BERRY",
	"ASPEAR BERRY",
	"LEPPA BERRY",
	"ORAN BERRY",
	"PERSIM BERRY",
	"LUM BERRY",
	"SITRUS BERRY",
	"FIGY BERRY",
	"WIKI BERRY",
	"MAGO BERRY",
	"AGUAV BERRY",
	"IAPAPA BERRY",
	"RAZZ BERRY",
	"BLUK BERRY",
	"NANAB BERRY",
	"WEPEAR BERRY",
	"PINAP BERRY",
	"POMEG BERRY",
	"KELPSY BERRY",
	"QUALOT BERRY",
	"HONDEW BERRY",
	"GREPA BERRY",
	"TAMATO BERRY",
	"CORNN BERRY",
	"MAGOST BERRY",
	"RABUTA BERRY",
	"NOMEL BERRY",
	"SPELON BERRY",
	"PAMTRE BERRY",
	"WATMEL BERRY",
	"DURIN BERRY",
	"BELUE BERRY",
	"LIECHI BERRY",
	"GANLON BERRY",
	"SALAC BERRY",
	"PETAYA BERRY",
	"APICOT BERRY",
	"LANSAT BERRY",
	"STARF BERRY",
	"ENIGMA BERRY",
	"????????",
	"????????",
	"????????",
	"BRIGHTPOWDER",
	"WHITE HERB",
	"MACHO BRACE",
	"EXP. SHARE",
	"QUICK CLAW",
	"SOOTHE BELL",
	"MENTAL HERB",
	"CHOICE BAND",
	"KING'S ROCK",
	"SILVERPOWDER",
	"AMULET COIN",
	"CLEANSE TAG",
	"SOUL DEW",
	"DEEPSEATOOTH",
	"DEEPSEASCALE",
	"SMOKE BALL",
	"EVERSTONE",
	"FOCUS BAND",
	"LUCKY EGG",
	"SCOPE LENS",
	"METAL COAT",
	"LEFTOVERS",
	"DRAGON SCALE",
	"LIGHT BALL",
	"SOFT SAND",
	"HARD STONE",
	"MIRACLE SEED",
	"BLACKGLASSES",
	"BLACK BELT",
	"MAGNET",
	"MYSTIC WATER",
	"SHARP BEAK",
	"POISON BARB",
	"NEVERMELTICE",
	"SPELL TAG",
	"TWISTEDSPOON",
	"CHARCOAL",
	"DRAGON FANG",
	"SILK SCARF",
	"UP-GRADE",
	"SHELL BELL",
	"SEA INCENSE",
	"LAX INCENSE",
	"LUCKY PUNCH",
	"METAL POWDER",
	"THICK CLUB",
	"STICK",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"????????",
	"RED SCARF",
	"BLUE SCARF",
	"PINK SCARF",
	"GREEN SCARF",
	"YELLOW SCARF",
	"MACH BIKE",
	"COIN CASE",
	"ITEMFINDER",
	"OLD ROD",
	"GOOD ROD",
	"SUPER ROD",
	"S.S. TICKET",
	"CONTEST PASS",
	"????????",
	"WAILMER PAIL",
	"PocketPC",
	"SOOT SACK",
	"BASEMENT KEY",
	"ACRO BIKE",
	"PoKeBlLoCk CASE",
	"LETTER",
	"EON TICKET",
	"RED ORB",
	"BLUE ORB",
	"PocketCenter",
	"GO-GOGGLES",
	"METEORITE",
	"RM. 1 KEY",
	"RM. 2 KEY",
	"RM. 4 KEY",
	"RM. 6 KEY",
	"STORAGE KEY",
	"ROOT FOSSIL",
	"CLAW FOSSIL",
	"DEVON SCOPE",
	"TM01",
	"TM02",
	"TM03",
	"TM04",
	"TM05",
	"TM06",
	"TM07",
	"TM08",
	"TM09",
	"TM10",
	"TM11",
	"TM12",
	"TM13",
	"TM14",
	"TM15",
	"TM16",
	"TM17",
	"TM18",
	"TM19",
	"TM20",
	"TM21",
	"TM22",
	"TM23",
	"TM24",
	"TM25",
	"TM26",
	"TM27",
	"TM28",
	"TM29",
	"TM30",
	"TM31",
	"TM32",
	"TM33",
	"TM34",
	"TM35",
	"TM36",
	"TM37",
	"TM38",
	"TM39",
	"TM40",
	"TM41",
	"TM42",
	"TM43",
	"TM44",
	"TM45",
	"TM46",
	"TM47",
	"TM48",
	"TM49",
	"TM50",
	"HM01",
	"HM02",
	"HM03",
	"HM04",
	"HM05",
	"HM06",
	"HM07",
	"HM08",
	"????????",
	"????????",
	"OAK'S PARCEL",
	"POKé FLUTE",
	"SECRET KEY",
	"BIKE VOUCHER",
	"GOLD TEETH",
	"OLD AMBER",
	"CARD KEY",
	"LIFT KEY",
	"HELIX FOSSIL",
	"DOME FOSSIL",
	"SILPH SCOPE",
	"BICYCLE",
	"TOWN MAP",
	"VS SEEKER",
	"FAME CHECKER",
	"TM CASE",
	"BERRY POUCH",
	"TEACHY TV",
	"TRI-PASS",
	"RAINBOW PASS",
	"TEA",
	"MYSTICTICKET",
	"AURORATICKET",
	"POWDER JAR",
	"RUBY",
	"SAPPHIRE",
}

ability = {
	"None", "None", "None",
	"Overgrow","None","None",
	"Overgrow","None","None",
	"Thick Fat","None","None",
	"Blaze","None","None",
	"Blaze","None","None",
	"Tough Claws","None","None",
	"Torrent","None","None",
	"Torrent","None","None",
	"Regenerator","None","None",
	"Shield Dust","None","None",
	"Shed Skin","None","None",
	"Compound Eyes","None","None",
	"Poison Point","None","None",
	"Shed Skin","None","None",
	"Adaptability","None","None",
	"Keen Eye","None","None",
	"Keen Eye","None","None",
	"Keen Eye","None","None",
	"Guts","None","None",
	"Guts","None","None",
	"Intimidate","None","None",
	"Intimidate","None","None",
	"Intimidate","None","None",
	"Intimidate","None","None",
	"Static","None","None",
	"Static","None","None",
	"Sand Force","None","None",
	"Sand Force","None","None",
	"Poison Point","None","None",
	"Poison Point","None","None",
	"Sheer Force","None","None",
	"Poison Touch","None","None",
	"Poison Touch","None","None",
	"Sheer Force","None","None",
	"Magic Guard","None","None",
	"Magic Guard","None","None",
	"Flash Fire","None","None",
	"Flash Fire","None","None",
	"Cute Charm","None","None",
	"Cute Charm","None","None",
	"Inner Focus","None","None",
	"Inner Focus","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Effect Spore","None","None",
	"Effect Spore","None","None",
	"Compound Eyes","None","None",
	"Shield Dust","None","None",
	"Sand Veil","None","None",
	"Sand Veil","None","None",
	"Pickup","None","None",
	"Limber","None","None",
	"Damp","None","None",
	"Damp","None","None",
	"Iron Fist","None","None",
	"Iron Fist","None","None",
	"Intimidate","None","None",
	"Intimidate","None","None",
	"Water Absorb","None","None",
	"Water Absorb","None","None",
	"Water Absorb","None","None",
	"Synchronize","None","None",
	"Synchronize","None","None",
	"Synchronize","None","None",
	"Guts","None","None",
	"Guts","None","None",
	"Guts","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Clear Body","None","None",
	"Clear Body","None","None",
	"Rock Head","None","None",
	"Rock Head","None","None",
	"Rock Head","None","None",
	"Run Away","None","None",
	"Run Away","None","None",
	"Oblivious","None","None",
	"Oblivious","None","None",
	"Magnet Pull","None","None",
	"Magnet Pull","None","None",
	"Keen Eye","None","None",
	"Run Away","None","None",
	"Run Away","None","None",
	"Thick Fat","None","None",
	"Thick Fat","None","None",
	"Stench","None","None",
	"Stench","None","None",
	"Shell Armor","None","None",
	"Shell Armor","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Cursed Body","None","None",
	"Rock Head","None","None",
	"Insomnia","None","None",
	"Insomnia","None","None",
	"Hyper Cutter","None","None",
	"Hyper Cutter","None","None",
	"Soundproof","None","None",
	"Soundproof","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Rock Head","None","None",
	"Rock Head","None","None",
	"Limber","None","None",
	"Iron Fist","None","None",
	"Own Tempo","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Lightning Rod","None","None",
	"Lightning Rod","None","None",
	"Natural Cure","None","None",
	"Chlorophyll","None","None",
	"Early Bird","None","None",
	"Swift Swim","None","None",
	"Poison Point","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Illuminate","None","None",
	"Illuminate","None","None",
	"Soundproof","None","None",
	"Swarm","None","None",
	"Oblivious","None","None",
	"Static","None","None",
	"Flame Body","None","None",
	"Hyper Cutter","None","None",
	"Intimidate","None","None",
	"Swift Swim","None","None",
	"Intimidate","None","None",
	"Water Absorb","None","None",
	"Limber","None","None",
	"Run Away","None","None",
	"Water Absorb","None","None",
	"Volt Absorb","None","None",
	"Flash Fire","None","None",
	"Trace","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Rock Head","None","None",
	"Thick Fat","None","None",
	"Pressure","None","None",
	"Pressure","None","None",
	"Pressure","None","None",
	"Shed Skin","None","None",
	"Shed Skin","None","None",
	"Inner Focus","None","None",
	"Pressure","None","None",
	"Synchronize","None","None",
	"Overgrow","None","None",
	"Overgrow","None","None",
	"Filter","None","None",
	"Blaze","None","None",
	"Blaze","None","None",
	"Adaptability","None","None",
	"Torrent","None","None",
	"Torrent","None","None",
	"Strong Jaw","None","None",
	"Run Away","None","None",
	"Run Away","None","None",
	"Compound Eyes","None","None",
	"Compound Eyes","None","None",
	"Technician","None","None",
	"Technician","None","None",
	"Poison Touch","None","None",
	"Sheer Force","None","None",
	"Inner Focus","None","None",
	"Volt Absorb","None","None",
	"Volt Absorb","None","None",
	"Static","None","None",
	"Cute Charm","None","None",
	"Cute Charm","None","None",
	"Hustle","None","None",
	"Hustle","None","None",
	"Synchronize","None","None",
	"Synchronize","None","None",
	"Static","None","None",
	"Static","None","None",
	"Static","None","None",
	"Chlorophyll","None","None",
	"Thick Fat","None","None",
	"Thick Fat","None","None",
	"Sturdy","None","None",
	"Water Absorb","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Technician","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Speed Boost","None","None",
	"Damp","None","None",
	"Damp","None","None",
	"Synchronize","None","None",
	"Synchronize","None","None",
	"Insomnia","None","None",
	"Oblivious","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Shadow Tag","None","None",
	"Inner Focus","None","None",
	"Sturdy","None","None",
	"Sturdy","None","None",
	"Serene Grace","None","None",
	"Hyper Cutter","None","None",
	"Rock Head","None","None",
	"Intimidate","None","None",
	"Intimidate","None","None",
	"Poison Point","None","None",
	"Swarm","None","None",
	"Sturdy","None","None",
	"Swarm","None","None",
	"Inner Focus","None","None",
	"Pickup","None","None",
	"Guts","None","None",
	"Magma Armor","None","None",
	"Magma Armor","None","None",
	"Oblivious","None","None",
	"Oblivious","None","None",
	"Hustle","None","None",
	"Hustle","None","None",
	"Suction Cups","None","None",
	"Vital Spirit","None","None",
	"Swift Swim","None","None",
	"Keen Eye","None","None",
	"Sheer Force","None","None",
	"Sheer Force","None","None",
	"Swift Swim","None","None",
	"Pickup","None","None",
	"Sturdy","None","None",
	"Trace","None","None",
	"Intimidate","None","None",
	"Own Tempo","None","None",
	"Steadfast","None","None",
	"Intimidate","None","None",
	"Oblivious","None","None",
	"Static","None","None",
	"Flame Body","None","None",
	"Thick Fat","None","None",
	"Natural Cure","None","None",
	"Pressure","None","None",
	"Pressure","None","None",
	"Pressure","None","None",
	"Guts","None","None",
	"Shed Skin","None","None",
	"Sand Stream","None","None",
	"Pressure","None","None",
	"Pressure","None","None",
	"Natural Cure","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"-------","None","None",
	"Overgrow","None","None",
	"Overgrow","None","None",
	"Technician","None","None",
	"Blaze","None","None",
	"Blaze","None","None",
	"Speed Boost","None","None",
	"Torrent","None","None",
	"Torrent","None","None",
	"Multiscale","None","None",
	"Run Away","None","None",
	"Intimidate","None","None",
	"Pickup","None","None",
	"Pickup","None","None",
	"Shield Dust","None","None",
	"Shed Skin","None","None",
	"No Guard","None","None",
	"Shed Skin","None","None",
	"Multiscale","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Tinted Lens","None","None",
	"Speed Boost","None","None",
	"Wonder Guard","None","None",
	"Guts","None","None",
	"Guts","None","None",
	"Effect Spore","None","None",
	"Effect Spore","None","None",
	"Own Tempo","None","None",
	"Keen Eye","None","None",
	"Keen Eye","None","None",
	"Swift Swim","None","None",
	"Intimidate","None","None",
	"Water Veil","None","None",
	"Water Veil","None","None",
	"Wonder Skin","None","None",
	"Wonder Skin","None","None",
	"Color Change","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Sturdy","None","None",
	"White Smoke","None","None",
	"Keen Eye","None","None",
	"Hydration","None","None",
	"Hydration","None","None",
	"Swift Swim","None","None",
	"Hyper Cutter","None","None",
	"Hyper Cutter","None","None",
	"Swift Swim","None","None",
	"Marvel Scale","None","None",
	"Rough Skin","None","None",
	"Strong Jaw","None","None",
	"Arena Trap","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Thick Fat","None","None",
	"Thick Fat","None","None",
	"Static","None","None",
	"Static","None","None",
	"Battle Armor","None","None",
	"Battle Armor","None","None",
	"Thick Fat","None","None",
	"Thick Fat","None","None",
	"Thick Fat","None","None",
	"Sand Veil","None","None",
	"Sand Veil","None","None",
	"Inner Focus","None","None",
	"Inner Focus","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Thick Fat","None","None",
	"Thick Fat","None","None",
	"Thick Fat","None","None",
	"Plus","None","None",
	"Minus","None","None",
	"Hyper Cutter","None","None",
	"Sheer Force","None","None",
	"Sheer Force","None","None",
	"Natural Cure","None","None",
	"Natural Cure","None","None",
	"Shadow Tag","None","None",
	"Levitate","None","None",
	"Pressure","None","None",
	"Natural Cure","None","None",
	"Truant","None","None",
	"Vital Spirit","None","None",
	"Truant","None","None",
	"Liquid Ooze","None","None",
	"Liquid Ooze","None","None",
	"Chlorophyll","None","None",
	"Soundproof","None","None",
	"Soundproof","None","None",
	"Soundproof","None","None",
	"Shell Armor","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Pressure","None","None",
	"Prankster","None","None",
	"Prankster","None","None",
	"Shed Skin","None","None",
	"Immunity","None","None",
	"Swift Swim","None","None",
	"Rock Head","None","None",
	"Rock Head","None","None",
	"Rock Head","None","None",
	"Forecast","None","None",
	"Illuminate","None","None",
	"Oblivious","None","None",
	"Storm Drain","None","None",
	"Storm Drain","None","None",
	"Battle Armor","None","None",
	"Battle Armor","None","None",
	"Synchronize","None","None",
	"Synchronize","None","None",
	"Synchronize","None","None",
	"Rock Head","None","None",
	"Rock Head","None","None",
	"Intimidate","None","None",
	"Clear Body","None","None",
	"Clear Body","None","None",
	"Clear Body","None","None",
	"Clear Body","None","None",
	"Clear Body","None","None",
	"Clear Body","None","None",
	"Drizzle","None","None",
	"Drought","None","None",
	"Air Lock","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Serene Grace","None","None",
	"Pressure","None","None",
	"Levitate","None","None",
	"-------","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Overgrow","None","None",
	"Overgrow","None","None",
	"Shell Armor","None","None",
	"Blaze","None","None",
	"Blaze","None","None",
	"Iron Fist","None","None",
	"Torrent","None","None",
	"Torrent","None","None",
	"Swift Swim","None","None",
	"Reckless","None","None",
	"Reckless","None","None",
	"Reckless","None","None",
	"Unaware","None","None",
	"Unaware","None","None",
	"Swarm","None","None",
	"Punk Rock","None","None",
	"Rivalry","None","None",
	"Rivalry","None","None",
	"Rivalry","None","None",
	"Natural Cure","None","None",
	"Natural Cure","None","None",
	"Sheer Force","None","None",
	"Sheer Force","None","None",
	"Battle Armor","None","None",
	"Battle Armor","None","None",
	"Shed Skin","None","None",
	"Grassy Surge","None","None",
	"Serene Grace","None","None",
	"Honey Gather","None","None",
	"Pressure","None","None",
	"Run Away","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Chlorophyll","None","None",
	"Flower Gift","None","None",
	"Sticky Hold","None","None",
	"Sticky Hold","None","None",
	"Technician","None","None",
	"Aftermath","None","None",
	"Aftermath","None","None",
	"Run Away","None","None",
	"Cute Charm","None","None",
	"Levitate","None","None",
	"Insomnia","None","None",
	"Limber","None","None",
	"Thick Fat","None","None",
	"Levitate","None","None",
	"Stench","None","None",
	"Stench","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Sturdy","None","None",
	"Soundproof","None","None",
	"Natural Cure","None","None",
	"Keen Eye","None","None",
	"Pressure","None","None",
	"Sand Veil","None","None",
	"Sand Veil","None","None",
	"Sand Veil","None","None",
	"Thick Fat","None","None",
	"Inner Focus","None","None",
	"Justified","None","None",
	"Sand Stream","None","None",
	"Sand Stream","None","None",
	"Battle Armor","None","None",
	"Battle Armor","None","None",
	"Dry Skin","None","None",
	"Dry Skin","None","None",
	"Levitate","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Snow Warning","None","None",
	"Snow Warning","None","None",
	"Pressure","None","None",
	"Magnet Pull","None","None",
	"Own Tempo","None","None",
	"Lightning Rod","None","None",
	"Chlorophyll","None","None",
	"Motor Drive","None","None",
	"Flame Body","None","None",
	"Hustle","None","None",
	"Speed Boost","None","None",
	"Leaf Guard","None","None",
	"Snow Cloak","None","None",
	"Hyper Cutter","None","None",
	"Oblivious","None","None",
	"Adaptability","None","None",
	"Steadfast","None","None",
	"Sturdy","None","None",
	"Pressure","None","None",
	"Snow Cloak","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Pressure","None","None",
	"Pressure","None","None",
	"Flash Fire","None","None",
	"Slow Start","None","None",
	"Pressure","None","None",
	"Levitate","None","None",
	"Hydration","None","None",
	"Hydration","None","None",
	"Bad Dreams","None","None",
	"Natural Cure","None","None",
	"Multitype","None","None",
	"Victory Star","None","None",
	"Overgrow","None","None",
	"Overgrow","None","None",
	"Marvel Scale","None","None",
	"Blaze","None","None",
	"Blaze","None","None",
	"Reckless","None","None",
	"Torrent","None","None",
	"Torrent","None","None",
	"Shell Armor","None","None",
	"Run Away","None","None",
	"Illuminate","None","None",
	"Vital Spirit","None","None",
	"Intimidate","None","None",
	"Intimidate","None","None",
	"Limber","None","None",
	"Limber","None","None",
	"Gluttony","None","None",
	"Gluttony","None","None",
	"Gluttony","None","None",
	"Gluttony","None","None",
	"Gluttony","None","None",
	"Gluttony","None","None",
	"Forewarn","None","None",
	"Forewarn","None","None",
	"Big Pecks","None","None",
	"Big Pecks","None","None",
	"Big Pecks","None","None",
	"Lightning Rod","None","None",
	"Lightning Rod","None","None",
	"Sturdy","None","None",
	"Sturdy","None","None",
	"Sturdy","None","None",
	"Unaware","None","None",
	"Unaware","None","None",
	"Sand Rush","None","None",
	"Sand Rush","None","None",
	"Healer","None","None",
	"Iron Fist","None","None",
	"Iron Fist","None","None",
	"Iron Fist","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Guts","None","None",
	"Sturdy","None","None",
	"Swarm","None","None",
	"Leaf Guard","None","None",
	"Swarm","None","None",
	"Poison Point","None","None",
	"Poison Point","None","None",
	"Poison Point","None","None",
	"Prankster","None","None",
	"Prankster","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Reckless","None","None",
	"Intimidate","None","None",
	"Intimidate","None","None",
	"Intimidate","None","None",
	"Hustle","None","None",
	"Sheer Force","None","None",
	"Water Absorb","None","None",
	"Sturdy","None","None",
	"Sturdy","None","None",
	"Shed Skin","None","None",
	"Shed Skin","None","None",
	"Wonder Skin","None","None",
	"Mummy","None","None",
	"Mummy","None","None",
	"Swift Swim","None","None",
	"Swift Swim","None","None",
	"Reckless","None","None",
	"Reckless","None","None",
	"Stench","None","None",
	"Stench","None","None",
	"Illusion","None","None",
	"Illusion","None","None",
	"Skill Link","None","None",
	"Skill Link","None","None",
	"Frisk","None","None",
	"Frisk","None","None",
	"Frisk","None","None",
	"Overcoat","None","None",
	"Overcoat","None","None",
	"Overcoat","None","None",
	"Keen Eye","None","None",
	"Keen Eye","None","None",
	"Ice Body","None","None",
	"Ice Body","None","None",
	"Ice Body","None","None",
	"Sap Sipper","None","None",
	"Sap Sipper","None","None",
	"Static","None","None",
	"Swarm","None","None",
	"Swarm","None","None",
	"Effect Spore","None","None",
	"Effect Spore","None","None",
	"Water Absorb","None","None",
	"Water Absorb","None","None",
	"Healer","None","None",
	"Compound Eyes","None","None",
	"Compound Eyes","None","None",
	"Iron Barbs","None","None",
	"Iron Barbs","None","None",
	"Plus","None","None",
	"Plus","None","None",
	"Plus","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Telepathy","None","None",
	"Telepathy","None","None",
	"Flash Fire","None","None",
	"Flash Fire","None","None",
	"Flash Fire","None","None",
	"Rivalry","None","None",
	"Rivalry","None","None",
	"Rivalry","None","None",
	"Snow Cloak","None","None",
	"Snow Cloak","None","None",
	"Levitate","None","None",
	"Hydration","None","None",
	"Hydration","None","None",
	"Static","None","None",
	"Regenerator","None","None",
	"Regenerator","None","None",
	"Rough Skin","None","None",
	"Iron Fist","None","None",
	"Iron Fist","None","None",
	"Defiant","None","None",
	"Defiant","None","None",
	"Reckless","None","None",
	"Keen Eye","None","None",
	"Keen Eye","None","None",
	"Stamina","None","None",
	"Stamina","None","None",
	"Gluttony","None","None",
	"Swarm","None","None",
	"Mold Breaker","None","None",
	"Mold Breaker","None","None",
	"Levitate","None","None",
	"Flame Body","None","None",
	"Flame Body","None","None",
	"Justified","None","None",
	"Justified","None","None",
	"Justified","None","None",
	"Prankster","None","None",
	"Prankster","None","None",
	"Turboblaze","None","None",
	"Teravolt","None","None",
	"Sand Force","None","None",
	"Pressure","None","None",
	"Justified","None","None",
	"Serene Grace","None","None",
	"Download","None","None",
	"Big Pecks","None","None",
	"Cursed Body","None","None",
	"Cursed Body","None","None",
	"-------","None","None",
	"Shed Skin","None","None",
	"Shed Skin","None","None",
	"Sand Force","None","None",
	"Iron Barbs","None","None",
	"Sticky Hold","None","None",
	"Sticky Hold","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Levitate","None","None",
	"Serene Grace","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Multitype","None","None",
	"Rock Head","None","None",
	"Zen Mode","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Chlorophyll","None","None",
	"Sand Stream","None","None",
	"Sand Stream","None","None",
	"Serene Grace","None","None",
	"Download","None","None",
	"Download","None","None",
	"Download","None","None",
	"Download","None","None",
	"Flower Gift","None","None",
	"Teravolt","None","None",
	"Turboblaze","None","None",
	"Regenerator","None","None",
	"Volt Absorb","None","None",
	"Intimidate","None","None",
	"Justified","None","None",
	"Overgrow","None","None",
	"Overgrow","None","None",
	"Iron Barbs","None","None",
	"Blaze","None","None",
	"Blaze","None","None",
	"Magician","None","None",
	"Torrent","None","None",
	"Torrent","None","None",
	"Protean","None","None",
	"Cheek Pouch","None","None",
	"Cheek Pouch","None","None",
	"Big Pecks","None","None",
	"Flame Body","None","None",
	"Flame Body","None","None",
	"Shield Dust","None","None",
	"Shed Skin","None","None",
	"Shield Dust","None","None",
	"Unnerve","None","None",
	"Unnerve","None","None",
	"Flower Gift","None","None",
	"Flower Gift","None","None",
	"Flower Gift","None","None",
	"Sap Sipper","None","None",
	"Sap Sipper","None","None",
	"Mold Breaker","None","None",
	"Mold Breaker","None","None",
	"Fur Coat","None","None",
	"Keen Eye","None","None",
	"Keen Eye","None","None",
	"No Guard","None","None",
	"No Guard","None","None",
	"Stance Change","None","None",
	"Healer","None","None",
	"Healer","None","None",
	"Sweet Veil","None","None",
	"Sweet Veil","None","None",
	"Contrary","None","None",
	"Contrary","None","None",
	"Tough Claws","None","None",
	"Tough Claws","None","None",
	"Adaptability","None","None",
	"Adaptability","None","None",
	"Mega Launcher","None","None",
	"Mega Launcher","None","None",
	"Dry Skin","None","None",
	"Dry Skin","None","None",
	"Strong Jaw","None","None",
	"Strong Jaw","None","None",
	"Refrigerate","None","None",
	"Refrigerate","None","None",
	"Cute Charm","None","None",
	"Limber","None","None",
	"Cheek Pouch","None","None",
	"Clear Body","None","None",
	"Sap Sipper","None","None",
	"Sap Sipper","None","None",
	"Sap Sipper","None","None",
	"Prankster","None","None",
	"Natural Cure","None","None",
	"Natural Cure","None","None",
	"Pickup","None","None",
	"Pickup","None","None",
	"Own Tempo","None","None",
	"Own Tempo","None","None",
	"Frisk","None","None",
}

curve={ 3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,3,3,3,0,0,0,0,0,0,0,0,0,0,3,3,3,3,3,3,4,4,0,0,4,4,0,0,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,5,5,3,3,3,3,3,3,3
,3,3,3,3,3,5,5,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,3,3,3,0,0,0,0,0,0,0,5,5,0,0,0,0,0,0,0,5,5,4,0,0,0,0,0,0,5,5,0,0,0,0,0,5,5,5,5,5,0,0,0,0
,0,0,0,0,0,0,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,3,0,0,0,0,4,4,4,4,0,5,5,0,4,4,4,4,0,0,3,3,3,3,4,4,0,3,3,3,3,4,3,3,0,0,0,0,0,3,0,4,0,0,0,0
,0,0,3,0,4,4,0,0,3,5,3,0,0,0,0,5,5,4,0,0,4,5,5,5,5,0,0,0,0,5,4,0,0,0,0,0,5,4,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,0,0,0,3,3,3,3
,3,3,3,3,0,0,5,5,5,0,0,2,2,5,5,5,1,1,1,3,3,3,2,2,4,0,4,4,3,4,5,5,5,0,0,5,5,0,0,1,2,3,2,2,5,5,2,2,0,0,0,4,4,4,3,3,3,3,3,1,1,1,2,4,4,0,0,2,2
,0,0,1,1,1,1,1,1,0,3,4,4,4,4,5,4,3,0,0,0,3,3,3,1,1,1,5,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3,3,3,3,3,1,1,1,1
,0,0,0,3,3,0,0,0,0,0,0,0,4,2,2,0,0,4,3,4,4,4,0,0,0,0,0,0,4,3,0,5,5,5,5,3,3,5,5,5,5,0,0,5,1,1,5,5,5,3,0,0,5,0,0,0,4,0,0,0,3,5,0,5,0,4,0,0,5
,5,5,5,5,5,5,5,5,5,5,5,3,5,5,3,3,3,3,3,3,3,3,3,0,0,3,3,3,0,0,0,0,0,0,0,0,4,4,3,3,3,0,0,3,3,3,0,0,0,0,4,3,3,3,3,3,3,0,0,3,3,3,3,3,3,0,0,0,0
,0,3,3,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,4,4,3,3,3,3,3,3,0,0,5,5,5,0,0,0,0,0,0,0,0,0,4,0,0,0,0,3,3,3,5,5,5,0,0,3,3,3,5,5,5,0,0,0,0,0,0
,3,3,0,0,0,0,0,0,5,5,5,5,0,0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,0,0,3,3,3,0,0,0,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
,0,0,0,0,5,5,0,0,0,0,0,0,0,0,0,5,5,5,5,4,0,0,0,0,0,0,0,0,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0
,0,0,0,0,3,3,3,4,5,5,0,0,0,0,4,5,5,0,5,0,0,0,0,0,0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,0,0,3,3,3,0,0
,0,4,4,0,0,0,0,0,0,4,4,3,3,3,1,1,1,0,0,0,5,5,3,3,0,0,3,3,0,0,5,5,5,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,5,5,4,0,0,0,5,5,5,5,0,5,5,5,5,5,5,5,5,5,5
,5,5,5,5,5,0,0,0,3,0,5,3,3,3,3,0,3,3,0,3,0,5,5,5,5,5,3,0,0,5,5,5,3,3,3,5,3,4,5,0,5,5,0,1,4,3,0,5,5,5,5,0,5,3,5,5,4,5,5,5,5,0,0,0,0,0,0,0,0
,0,0,0,3,3,3,0,0,5,0,0,0,0,0,0,0,0,0,5,5,5,0,4,0,0,3,3,0,0,5,5,0,0,3,0,3,3,0,3,3,5,5,5,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,5,5,5,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,0,3,3,0,0,0,0,0,0,5,5
,5,5,5,5,5,5,5,5,5,5,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,5,5,5,5,0,0
,0,0,0,0,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,5,5,0,0,3,0,0,0,0,0,0,0,0,0,0,5,4,0,5,5,5,5,5,5,5,5}

nature = {"Hardy","Lonely","Brave","Adamant","Naughty",
			"Bold","Docile","Relaxed","Impish","Lax",
			"Timid","Hasty","Serious","Jolly","Naive",
			"Modest","Mild","Quiet","Bashful","Rash",
			"Calm","Gentle","Sassy","Careful","Quirky"}

charmap = { [0]=
	" ", "À", "Á", "Â", "Ç", "È", "É", "Ê", "Ë", "Ì", "こ", "Î", "Ï", "Ò", "Ó", "Ô",
	"Œ", "Ù", "Ú", "Û", "Ñ", "ß", "à", "á", "ね", "ç", "è", "é", "ê", "ë", "ì", "ま",
	"î", "ï", "ò", "ó", "ô", "œ", "ù", "ú", "û", "ñ", "º", "ª", "�", "&", "+", "あ",
	"ぃ", "ぅ", "ぇ", "ぉ", "v", "=", "ょ", "が", "ぎ", "ぐ", "げ", "ご", "ざ", "じ", "ず", "ぜ",
	"ぞ", "だ", "ぢ", "づ", "で", "ど", "ば", "び", "ぶ", "べ", "ぼ", "ぱ", "ぴ", "ぷ", "ぺ", "ぽ",
	"っ", "¿", "¡", "P\u{200d}k", "M\u{200d}n", "P\u{200d}o", "K\u{200d}é", "�", "�", "�", "Í", "%", "(", ")", "セ", "ソ",
	"タ", "チ", "ツ", "テ", "ト", "ナ", "ニ", "ヌ", "â", "ノ", "ハ", "ヒ", "フ", "ヘ", "ホ", "í",
	"ミ", "ム", "メ", "モ", "ヤ", "ユ", "ヨ", "ラ", "リ", "⬆", "⬇", "⬅", "➡", "ヲ", "ン", "ァ",
	"ィ", "ゥ", "ェ", "ォ", "ャ", "ュ", "ョ", "ガ", "ギ", "グ", "ゲ", "ゴ", "ザ", "ジ", "ズ", "ゼ",
	"ゾ", "ダ", "ヂ", "ヅ", "デ", "ド", "バ", "ビ", "ブ", "ベ", "ボ", "パ", "ピ", "プ", "ペ", "ポ",
	"ッ", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "!", "?", ".", "-", "・",
	"…", "“", "”", "‘", "’", "♂", "♀", "$", ",", "×", "/", "A", "B", "C", "D", "E",
	"F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U",
	"V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",
	"l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "▶",
	":", "Ä", "Ö", "Ü", "ä", "ö", "ü", "⬆", "⬇", "⬅", "�", "�", "�", "�", "�", ""
}

local terminator=0xFF
local monNameLength=10
local speciesNameLength=11
local playerNameLength=10
local boxMonSize=80
local partyMonSize=100
local partyloc=0x202402C --gEnemyParty
local partyCount=0x202402A  --gEnemyPartyCount
local storageLoc=0x2029314 -- gPokemonStorage
-- local storageLoc=0x3005010  -- gPokemonStorage
local speciesNameTable=0x3185c8


function slowCurve(n)
    return math.floor((5*(n^3))/4)
end
function fastCurve(n)
    return math.floor((4*(n^3))/5)
end
function medfastCurve(n)
    return n^3
end
function medslowCurve(n)
    return math.floor((6 * (n)^3) / 5) - (15 * (n)^2) + (100 * n) - 140
end
function erraticCurve(n)
    if (n<=50) then
        return math.floor(((100 - n)*n^3)/50)
    end
    if (n<=68) then
        return math.floor(((150 - n)*n^3)/100)
    end
    if (n<=98) then
        return math.floor(math.floor((1911 - 10 * n) / 3) * n^3 / 500)
    end
    return math.floor((160 - n) * n^3 / 100)
end
function flutuatingCurve(n)
	if (n<15) then
	  return math.floor((math.floor((n + 1) / 3) + 24) * n^3 / 50)
	end
	if (n<=36) then
		return math.floor((n + 14) * n^3 / 50)
	end
	return math.floor((math.floor(n / 2) + 32) * n^3 / 50)
end

function calcLevel(exp, species)
	level = 1
	while (exp>=expRequired(species,level+1)) do
		level=level+1
	end
	return level
end

function expRequired(species,level)
	-- expCurve = curve[species]
	return slowCurve(level) -- TODO: Ensure this is actually a viable path forward.
	-- if (expCurve == 0) then return medfastCurve(level) end
	-- if (expCurve == 1) then return erraticCurve(level) end
	-- if (expCurve == 2) then return flutuatingCurve(level) end
	-- if (expCurve == 3) then return medslowCurve(level) end
	-- if (expCurve == 4) then return fastCurve(level) end
	-- if (expCurve == 5) then return slowCurve(level) end
end

function getParty()
	local party = {}
	local monStart = partyloc
	for i = 1, 6 do
		party[i] = readPartyMon(monStart)
		monStart = monStart + partyMonSize
	end
	return party
end

function toString(rawstring)
	local string = ""
	for _, char in ipairs({rawstring:byte(1, #rawstring)}) do
		if char == terminator then
			break
		end
		string = string..charmap[char]
	end
	return string
end

function _read16BE(emu, address)
	return (emu:read8(address) << 8) | emu:read8(address + 1)
end

function readFullBoxMon(address)
	local mon = {}
	mon.personality = emu:read32(address + 0)
	mon.otId = emu:read32(address + 4)
	mon.nickname = toString(emu:readRange(address + 8, monNameLength))

	mon.species = emu:read32(address + 28) & 0xFFFF
	mon.item = emu:read32(address + 28) >> 16
	mon.experience = emu:read32(address + 32)

	chunks = {
		emu:read8(address + 39),
		emu:read8(address + 40),
		emu:read8(address + 41),
		emu:read8(address + 42),
		emu:read8(address + 43),
	}

	mon.moves = {
		(chunks[5] << 2) + (chunks[4] >> 6),
		((chunks[4] & 0x3F) << 4) + (chunks[3] >> 4),
		((chunks[3] & 0x0F) << 6) + (chunks[2] >> 2),
		((chunks[2] & 0x03) << 8) + chunks[1],
	}

	mon.hpEV = emu:read8(address + 44)
	mon.attackEV = emu:read8(address + 45)
	mon.defenseEV = emu:read8(address + 46)
	mon.speedEV = emu:read8(address + 47)
	mon.spAttackEV = emu:read8(address + 48)
	mon.spDefenseEV = emu:read8(address + 49)

	ivBlock = emu:read32(address + 54)
	mon.hpIV = (ivBlock >> 0) & 0x1F
	mon.attackIV = (ivBlock >> 5) & 0x1F
	mon.defenseIV = (ivBlock >> 10) & 0x1F
	mon.speedIV = (ivBlock >> 15) & 0x1F
	mon.spAttackIV = (ivBlock >> 20) & 0x1F
	mon.spDefenseIV = (ivBlock >> 25) & 0x1F

	-- TODO: Fix this to actually select abilities if multiple
	--   abilities ever end up being present.
	mon.altAbility = 0

	return mon
end

function readBoxMon(address)
	local mon = {}
	mon.personality = emu:read32(address + 0)
	mon.otId = emu:read32(address + 4)
	mon.nickname = toString(emu:readRange(address + 8, monNameLength))
	mon.language = emu:read8(address + 18)
	local flags = emu:read8(address + 19)
	mon.isBadEgg = flags & 1
	mon.hasSpecies = (flags >> 1) & 1
	mon.isEgg = (flags >> 2) & 1
	mon.otName = toString(emu:readRange(address + 20, playerNameLength))
	mon.markings = emu:read8(address + 27)

	local key = mon.otId ~ mon.personality
	local substructSelector = {
		[ 0] = {0, 1, 2, 3},
		[ 1] = {0, 1, 3, 2},
		[ 2] = {0, 2, 1, 3},
		[ 3] = {0, 3, 1, 2},
		[ 4] = {0, 2, 3, 1},
		[ 5] = {0, 3, 2, 1},
		[ 6] = {1, 0, 2, 3},
		[ 7] = {1, 0, 3, 2},
		[ 8] = {2, 0, 1, 3},
		[ 9] = {3, 0, 1, 2},
		[10] = {2, 0, 3, 1},
		[11] = {3, 0, 2, 1},
		[12] = {1, 2, 0, 3},
		[13] = {1, 3, 0, 2},
		[14] = {2, 1, 0, 3},
		[15] = {3, 1, 0, 2},
		[16] = {2, 3, 0, 1},
		[17] = {3, 2, 0, 1},
		[18] = {1, 2, 3, 0},
		[19] = {1, 3, 2, 0},
		[20] = {2, 1, 3, 0},
		[21] = {3, 1, 2, 0},
		[22] = {2, 3, 1, 0},
		[23] = {3, 2, 1, 0},
	}

	local pSel = substructSelector[mon.personality % 24]
	local ss0 = {}
	local ss1 = {}
	local ss2 = {}
	local ss3 = {}

	for i = 0, 2 do
		ss0[i] = emu:read32(address + 32 + i * 4)
		ss1[i] = emu:read32(address + 44 + i * 4)
		ss2[i] = emu:read32(address + 56 + i * 4)
		ss3[i] = emu:read32(address + 68 + i * 4)
	end

	mon.species = ss0[0] & 0xFFFF
	mon.heldItem = ss0[0] >> 16
	mon.experience = ss0[1]
	mon.ppBonuses = ss0[2] & 0xFF
	mon.friendship = (ss0[2] >> 8) & 0xFF
	mon.hiddenNature = (ss0[2] >> 16) & 0x1F

	mon.moves = {
		ss1[0] & 0xFFFF,
		ss1[0] >> 16,
		ss1[1] & 0xFFFF,
		ss1[1] >> 16
	}
	mon.pp = {
		ss1[2] & 0xFF,
		(ss1[2] >> 8) & 0xFF,
		(ss1[2] >> 16) & 0xFF,
		ss1[2] >> 24
	}

	mon.hpEV = ss2[0] & 0xFF
	mon.attackEV = (ss2[0] >> 8) & 0xFF
	mon.defenseEV = (ss2[0] >> 16) & 0xFF
	mon.speedEV = ss2[0] >> 24
	mon.spAttackEV = ss2[1] & 0xFF
	mon.spDefenseEV = (ss2[1] >> 8) & 0xFF
	mon.cool = (ss2[1] >> 16) & 0xFF
	mon.beauty = ss2[1] >> 24
	mon.cute = ss2[2] & 0xFF
	mon.smart = (ss2[2] >> 8) & 0xFF
	mon.tough = (ss2[2] >> 16) & 0xFF
	mon.sheen = ss2[2] >> 24

	mon.pokerus = ss3[0] & 0xFF
	mon.metLocation = (ss3[0] >> 8) & 0xFF
	flags = ss3[0] >> 16
	mon.metLevel = flags & 0x7F
	mon.metGame = (flags >> 7) & 0xF
	mon.pokeball = (flags >> 11) & 0xF
	mon.otGender = (flags >> 15) & 0x1
	flags = ss3[1]
	mon.hpIV = (flags) & 0x1F
	mon.attackIV = (flags >> 5) & 0x1F
	mon.defenseIV = (flags >> 10) & 0x1F
	mon.speedIV = (flags >> 15) & 0x1F
	mon.spAttackIV = (flags >> 20) & 0x1F
	mon.spDefenseIV = (flags >> 25) & 0x1F
	-- Bit 30 is another "isEgg" bit
	flags = ss3[2]
	mon.coolRibbon = flags & 7
	mon.beautyRibbon = (flags >> 3) & 7
	mon.cuteRibbon = (flags >> 6) & 7
	mon.smartRibbon = (flags >> 9) & 7
	mon.toughRibbon = (flags >> 12) & 7
	mon.championRibbon = (flags >> 15) & 1
	mon.winningRibbon = (flags >> 16) & 1
	mon.victoryRibbon = (flags >> 17) & 1
	mon.artistRibbon = (flags >> 18) & 1
	mon.effortRibbon = (flags >> 19) & 1
	mon.marineRibbon = (flags >> 20) & 1
	mon.landRibbon = (flags >> 21) & 1
	mon.skyRibbon = (flags >> 22) & 1
	mon.countryRibbon = (flags >> 23) & 1
	mon.nationalRibbon = (flags >> 24) & 1
	mon.earthRibbon = (flags >> 25) & 1
	mon.worldRibbon = (flags >> 26) & 1
	mon.altAbility = (flags >> 29) & 3
	return mon
end

function readPartyMon(address)
	local mon = readBoxMon(address)
	mon.status = emu:read32(address + 80)
	mon.level = emu:read8(address + 84)
	mon.mail = emu:read32(address + 85)
	mon.hp = emu:read16(address + 86)
	mon.maxHP = emu:read16(address + 88)
	mon.attack = emu:read16(address + 90)
	mon.defense = emu:read16(address + 92)
	mon.speed = emu:read16(address + 94)
	mon.spAttack = emu:read16(address + 96)
	mon.spDefense = emu:read16(address + 98)
	return mon
end

function getAbility(mon)
    current = ability[(mon.species*3)+1+mon.altAbility]
    if (current == "None") then
        current = ability[(mon.species*3)+1]
    end
    return current
end

function getNature(mon)
	return nature[(mon.personality % 25)+1]
end

function getPartyPrint(mon)
	str = ""
	str = str .. mons[mon.species]
	if (item[mon.heldItem]) then
		str = str .. string.format(" @ %s", item[mon.heldItem])
	end
	str = str .. string.format("\n")
	str = str .. "Ability: " .. string.format("%s", getAbility(mon)) .. string.format("\n")
	str = str .. string.format("Level: %d\n", mon.level)
	str = str .. string.format("%s", getNature(mon)) .. " Nature" .. string.format("\n")
	str = str .. string.format("IVs: %d HP / %d Atk / %d Def / %d SpA / %d SpD / %d Spe", mon.hpIV, mon.attackIV, mon.defenseIV, mon.spAttackIV, mon.spDefenseIV, mon.speedIV) .. string.format("\n")
	str = str .. string.format("EVs: %d HP / %d Atk / %d Def / %d SpA / %d SpD / %d Spe", mon.hpEV, mon.attackEV, mon.defenseEV, mon.spAttackEV, mon.spDefenseEV, mon.speedEV) .. string.format("\n")
	str = str .. string.format("Stats: %d HP / %d Atk / %d Def / %d SpA / %d SpD / %d Spe", mon.hp, mon.attack, mon.defense, mon.spAttack, mon.spDefense, mon.speed) .. string.format("\n")
	for i=1,4 do
		local mv = move[mon.moves[i] + 1]
		if(mv == "Hidden Power") then
			str = str .. string.format("- Hidden Power %s\n", getHP(mon))
			else
			if(mv ~= "") then
				str = str .. "- " .. mv .. "\n"
			end
		end
	end
	str = str .. string.format("\n")
	return str
end

function getPCPrint(mon)
	str = ""
	str = str ..  mons[mon.species]
	if (item[mon.heldItem]) then
		str = str .. string.format(" @ %s", item[mon.heldItem])
	end
	str = str .. string.format("\n")
	str = str .. "Ability: " .. string.format("%s", getAbility(mon)) .. string.format("\n")
	str = str .. string.format("Level: %d\n", calcLevel(mon.experience, mon.species))
	str = str .. string.format("%s", getNature(mon)) .. " Nature" .. string.format("\n")
	str = str .. string.format("IVs: %d HP / %d Atk / %d Def / %d SpA / %d SpD / %d Spe", mon.hpIV, mon.attackIV, mon.defenseIV, mon.spAttackIV, mon.spDefenseIV, mon.speedIV) .. string.format("\n")
	str = str .. string.format("EVs: %d HP / %d Atk / %d Def / %d SpA / %d SpD / %d Spe", mon.hpEV, mon.attackEV, mon.defenseEV, mon.spAttackEV, mon.spDefenseEV, mon.speedEV) .. string.format("\n")
	for i=1,4 do
		local mv = move[mon.moves[i] + 1]
		if(mv == "Hidden Power") then
			str = str .. string.format("- Hidden Power %s\n", getHP(mon))
			else
			if(mv ~= "") then
				str = str .. "- " .. mv .. "\n"
			end
		end
	end
	str = str .. string.format("\n")
	return str
end

function printPartyStatus(buffer)
    address = storageLoc + 4
	storageData = emu:read8(storageLoc)
    i = 0
	buffer:clear()
	for _, mon in ipairs(getParty()) do
		if (mon.species ~= 0) then
			buffer:print(getPartyPrint(mon))
		end
	end
    while i<0 do
		if (emu:read32(address) ~=0) then 
			buffer:print(getPCPrint(readFullBoxMon(address)))
		end
		i = i+1
		address = address + 58
	end
end

function getHP(mon)
    hptype = ((mon.hpIV%2 + (2*(mon.attackIV%2))+(4*(mon.defenseIV%2))+(8*(mon.speedIV%2))+(16*(mon.spAttackIV%2))+(32*(mon.spDefenseIV%2)))*5)/21
    hptype = math.floor(hptype)
	if (hptype == 0) then
		return "Fighting"
	end
	if (hptype == 1) then
		return "Flying"
	end
	if (hptype == 2) then
		return "Poison"
	end
	if (hptype == 3) then
		return "Ground"
	end
	if (hptype == 4) then
		return "Rock"
	end
	if (hptype ==5) then
		return "Bug"
	end
	if (hptype == 6) then
		return "Ghost"
	end
	if (hptype ==7) then
		return "Steel"
	end
	if (hptype == 8) then
		return "Fire"
	end
	if (hptype == 9) then
		return "Water"
	end
	if (hptype == 10) then
		return "Grass"
	end
	if (hptype == 11) then
		return "Electric"
	end
	if (hptype == 12) then
		return "Psychic"
	end
	if (hptype == 13) then
		return "Ice"
	end
	if (hptype == 14) then
		return "Dragon"
	end
	if (hptype == 15) then
		return "Dark"
	end
end

function getHiddens(buffer)
	address = storageLoc + 4
	i = 0
	buffer:clear()
	for _, mon in ipairs(getParty()) do
		if (mon.species ~= 0) then
			buffer:print(string.format("%s - %s\n", mons[mon.species], getHP(mon)))
		end
	end
	while i<120 do
		if (emu:read32(address) ~=0) then 
			buffer:print(string.format("%s - %s\n",mons[readBoxMon(address).species], getHP(readBoxMon(address))))
		end
		i = i+1
		address = address + 80
	end
end

function hiddens()
	if not hiddenBuffer then
		console:log("error")
		return
	end
	getHiddens(hiddenBuffer)
end

function startScript()
	console:log('To update your exports type "export()"')
	if not partyBuffer then
		partyBuffer = console:createBuffer("Showdown Export")
		partyBuffer:setSize(300,1000)
		export()
	end
	-- if not hiddenBuffer then
	-- 	hiddenBuffer = console:createBuffer("Hidden Powers")
	-- 	hiddenBuffer:setSize(200,200)
	-- 	hiddens()
	-- end
end

function export()
	if not partyBuffer then
		console:log("error")
		return
	end
	printPartyStatus(partyBuffer)
	-- if not hiddenBuffer then
	-- 	console:log("error")
	-- 	return
	-- end
	-- hiddens()
end

callbacks:add("start", startScript)
if emu then
	startScript()
end